name: Build wheels and release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1) build package
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python and uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.12'

      - name: Build wheels and sdist
        run: |
          uv build

      # 2) Create GitHub release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }} # Get tag name without the refs/tags/ prefix
          name: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            dist/*.whl
            dist/*.tar.gz

      # 3) Upload to PyPI
      - name: Upload to PyPI
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.TWINE_PASSWORD }}
        run: |
          uv publish




