name: Test on Push (Linux & Windows)

on:
  push:
    branches:
      - test  # or your default branch
  pull_request:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'dev'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.12]  # Add more versions if needed

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        if: runner.os == 'Linux'
        run: |
            python -m pip install poetry
        shell: bash

      - name: Add Poetry to PATH
        if: runner.os == 'Linux'
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH
        shell: bash

      - name: Install dependencies
        if: runner.os == 'Linux'
        run: poetry install

      - name: Run tests
        run: poetry run python -W ignore -m unittest
